### PR TITLE
Made usable with Django 1.10

### PR DESCRIPTION
**Pull request by rantonov**
Very simple changes to make it work with Django 1.10

### CODE REVIEW

**Comment by Edke** [comment]
@rantonov forked and merged your fix for Dj1.10, thank you !

**Comment by jonathanpglick** [comment]
@rantonov Thanks for this!

@seddonym Any chance this will get merged soon?

**Comment by seddonym** [comment]
Thanks so much for this PR, and sorry for taking so long to reply. As you've probably noticed, I've not been actively maintaining this package. I created it a long time ago for a personal project when I was quite new to Python. I didn't realise anyone was using it!

I'd be happy to merge this in, but I think the responsible thing to do is probably leave it as it is until there are some tests to prove it's backward compatible with older versions of Django, just in case it breaks someone's build.

Tox would be a good tool for this. Unfortunately I don't have the capacity to do this at the moment but if you would like to add that to the PR I'd be happy to review it.

**Comment by seddonym** [comment]
I've now added a test suite and updated the codebase (with thanks to @rantonov) so that it works with Django 1.8 - 1.11. I'm closing this PR but some of @rantonov's work was used.

**Pull request closed without merging**
